import '../../ng/app'

import '../../ng/components/login/login'
import '../../ng/components/settings-panel/settings-panel'
import '../../ng/components/side-toolbar/side-toolbar'
import '../../ng/components/chat-input/chat-input'
import '../../ng/components/chat-output/chat-output'
import '../../ng/components/chat-tabs/chat-tabs'
import '../../ng/components/user-panel/user-panel'
import '../../ng/components/thumbnail/thumbnail'
import '../../ng/components/chatters/chatters'
import '../../ng/components/chatters-tabs/chatters-tabs'
import '../../ng/components/add-channel/add-channel'
import '../../ng/components/emote-menu/emote-menu'

import '../../ng/providers/store'
import '../../ng/providers/settings'
import '../../ng/providers/open-external'
import '../../ng/providers/session'
import '../../ng/providers/manifest'
import '../../ng/providers/irc'
import '../../ng/providers/messages'
import '../../ng/providers/highlights'
import '../../ng/providers/notifications'
import '../../ng/providers/settings-gui'
import '../../ng/providers/emotes-twitch'

import '../../ng/directives/tab-completion.directive'
import '../../ng/directives/href-external.directive'
import '../../ng/directives/auto-focus.directive'
import '../../ng/directives/bind-html-compile.directive'
